### ISSUE TITLE
Crash on Minecraft 1.13.2 server startup

### ISSUE THREAD

**Issue by LostLuma** [OrnitheMC/ornithe-standard-libraries#15]
While testing something for a mod I'm working on I found using OSL on a 1.13.2 server will crash the game as it can not find a class. Here's the full [Minecraft log](https://files.lostluma.net/SkYpFQ.txt) output.

**Comment by SpaceWalkerRS** [comment]
That's a strange error, the `C_8105098` class it failed to find, that's the `Minecraft` class, so I'd wager one of the Mixins into that class failed which in turn caused the game to fail to load that class. Without seeing what that failure is though I cannot say what the issue is. 
One idea I have is that recent changes to the entrypoints system in Loader require an update for OSL. You could try downgrading Loader to 0.21-beta.2and see if that helps.

**Comment by LostLuma** [comment]
I don't think this is related to the entrypoint changes, as using the newest Fabric Loader version gives a different crash (missing `net.fabricmc.loader.impl.entrypoint.EntrypointUtils`). Using an older Fabric Loader version, or seemingly any Quilt Loader version does produce this exact crash every time though.

**Comment by SpaceWalkerRS** [comment]
I see, thanks for testing that. I'll investigate this further, 'cause it's definitely an OSL issue then!

**Comment by SpaceWalkerRS** [comment]
It appears to be an issue with the pack format detection](https://github.com/OrnitheMC/ornithe-standard-libraries/blob/3f6e50ca04dc884abf350f0ada14782eae0fe7e0/libraries/resource-loader/resource-loader-mc17w43a-mc1.13.2/src/main/java/net/ornithemc/osl/resource/loader/impl/ResourceLoader.java#L32), it attempts to access something that doesn't exist in the dedicated server environment.

**Comment by SpaceWalkerRS** [comment]
I reckon this was not an issue in 1.12 and below because those versions don't have data packs, so it never runs this code on the server environment.

**Comment by LostLuma** [comment]
Sounds pretty reasonable 🙂

**Comment by SpaceWalkerRS** [comment]
should be fixed in v0.10.4!

**Comment by LostLuma** [comment]
Just tested and it seems to work, thank you!
